package com.example.data.local

import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

object SampleData {

    fun getSampleEvaluations(): List<EvaluationEntity> {
        val sdf = SimpleDateFormat("yyyy-MM-dd", Locale.getDefault())
        val today = sdf.format(Date())
        val yesterday = sdf.format(Date(System.currentTimeMillis() - 86400000L))
        val threeDaysAgo = sdf.format(Date(System.currentTimeMillis() - 3 * 86400000L))

        return listOf(
            EvaluationEntity(
                id = "sample-1",
                fecha = today,
                tecnico = "Ing. Carlos Mendoza",
                campana = "2025-2026",
                sector = "Sector Norte",
                turno = "Turno 01",
                lote = "Lote K-04",
                valvula = "Válvula 02",
                variedad = "Kent",
                planta = "P1",
                tipoHoja = "Madura",
                durezaHoja = "Dura",
                longitudBrote = 18.5,
                tinturacionYemas = "75% (Alta)",
                tinturacionPorcentaje = 75.0,
                yemaApta = true,
                yemaHinchada = 35.0,
                yemaPicoLoro = 45.0,
                yemasAbiertas = 10.0,
                yemasCerradas = 10.0,
                yemaVegetativa = 0.0,
                yemaFloral = 90.0,
                emergenciaPanicula = 3.5,
                paniculasPorM2 = 8.0,
                longitudPanicula = 12.0,
                florAbierta = 20.0,
                cuajado = 5.0,
                frutosPorPanicula = 0.0,
                observaciones = "Excelente respuesta a inducción. Yema pico loro bien definida con buena tinturación en la base.",
                syncStatus = "SINCRONIZADO",
                remoteId = "REM-KENT-SAMPLE1"
            ),
            EvaluationEntity(
                id = "sample-2",
                fecha = today,
                tecnico = "Ing. Carlos Mendoza",
                campana = "2025-2026",
                sector = "Sector Norte",
                turno = "Turno 01",
                lote = "Lote K-04",
                valvula = "Válvula 02",
                variedad = "Kent",
                planta = "P2",
                tipoHoja = "Madura",
                durezaHoja = "Dura",
                longitudBrote = 17.0,
                tinturacionYemas = "50% (Moderada)",
                tinturacionPorcentaje = 50.0,
                yemaApta = true,
                yemaHinchada = 40.0,
                yemaPicoLoro = 30.0,
                yemasAbiertas = 5.0,
                yemasCerradas = 25.0,
                yemaVegetativa = 10.0,
                yemaFloral = 65.0,
                emergenciaPanicula = 1.2,
                paniculasPorM2 = 5.0,
                longitudPanicula = 8.5,
                florAbierta = 5.0,
                cuajado = 0.0,
                frutosPorPanicula = 0.0,
                observaciones = "Avance uniforme en planta P2. Presencia moderada de yema hinchada.",
                syncStatus = "PENDIENTE"
            ),
            EvaluationEntity(
                id = "sample-3",
                fecha = yesterday,
                tecnico = "Ing. Lucía Torres",
                campana = "2025-2026",
                sector = "Sector Sur",
                turno = "Turno 02",
                lote = "Lote K-09",
                valvula = "Válvula 05",
                variedad = "Kent",
                planta = "P1",
                tipoHoja = "Joven",
                durezaHoja = "Tierna",
                longitudBrote = 12.0,
                tinturacionYemas = "25% (Ligera)",
                tinturacionPorcentaje = 25.0,
                yemaApta = false,
                yemaHinchada = 20.0,
                yemaPicoLoro = 10.0,
                yemasAbiertas = 0.0,
                yemasCerradas = 70.0,
                yemaVegetativa = 60.0,
                yemaFloral = 10.0,
                emergenciaPanicula = 0.0,
                paniculasPorM2 = 0.0,
                longitudPanicula = 0.0,
                florAbierta = 0.0,
                cuajado = 0.0,
                frutosPorPanicula = 0.0,
                observaciones = "Brotes aún tiernos en Lote K-09. Esperar maduración foliar antes de considerar estimulación.",
                syncStatus = "PENDIENTE"
            ),
            EvaluationEntity(
                id = "sample-4",
                fecha = threeDaysAgo,
                tecnico = "Ing. Lucía Torres",
                campana = "2025-2026",
                sector = "Sector Este",
                turno = "Turno 03",
                lote = "Lote K-12",
                valvula = "Válvula 01",
                variedad = "Kent",
                planta = "P3",
                tipoHoja = "Madura",
                durezaHoja = "Intermedia",
                longitudBrote = 16.0,
                tinturacionYemas = "50% (Moderada)",
                tinturacionPorcentaje = 50.0,
                yemaApta = true,
                yemaHinchada = 50.0,
                yemaPicoLoro = 20.0,
                yemasAbiertas = 0.0,
                yemasCerradas = 30.0,
                yemaVegetativa = 20.0,
                yemaFloral = 50.0,
                emergenciaPanicula = 0.5,
                paniculasPorM2 = 3.0,
                longitudPanicula = 5.0,
                florAbierta = 0.0,
                cuajado = 0.0,
                frutosPorPanicula = 0.0,
                observaciones = "Inducción floral media. Requisito de humedad controlado.",
                syncStatus = "SINCRONIZADO",
                remoteId = "REM-KENT-SAMPLE4"
            )
        )
    }
}
